package com.sislog.gui;
import java.sql.Date;
import java.text.*;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Matheus
 */
public class GUI_TelaCadastro extends javax.swing.JFrame {
    MaskFormatter mascaraData;
    
    public GUI_TelaCadastro() {
        try {
            /*Componente que recebe a data de nascimento do ususario.
            Deve ser declarado antes da inicializacao dos componentes.*/
            mascaraData = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            System.out.println("Ocorreu um erro na criação da mascara do"
                    + " componente data:\n\n" + ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JLabel();
        txtCidade = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblNomeUser = new javax.swing.JTextField();
        lblTelefoneUser = new javax.swing.JTextField();
        lblEmailUser = new javax.swing.JTextField();
        lblCidadeUser = new javax.swing.JComboBox<>();
        lblDataUser = new javax.swing.JFormattedTextField(mascaraData);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtNome.setText("Nome:");

        txtTelefone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTelefone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTelefone.setText("Telefone:");

        txtCidade.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtCidade.setText("Cidade:");

        txtEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtEmail.setText("Email:");

        txtData.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtData.setText("Data de Nascimento:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Para se cadastrar inisra seus dados abaixo:");
        jScrollPane1.setViewportView(jTextArea1);

        lblNomeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblNomeUserActionPerformed(evt);
            }
        });

        lblTelefoneUser.setToolTipText("(DD)9000-0000");
        lblTelefoneUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblTelefoneUserActionPerformed(evt);
            }
        });

        lblEmailUser.setText("jTextField1");
        lblEmailUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblEmailUserActionPerformed(evt);
            }
        });

        lblCidadeUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCidadeUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "________", "Aracaju", "Belo Horizonte", "Belém", "Boa Vista", "Brasília", "Campo Grande", "Cuiabá", "Curitiba", "Florianópolis", "Fortaleza", "Goiânia", "João Pessoa", "Macapá", "Maceió", "Manaus", "Natal", "Palmas", "Porto Alegre", "Porto Velho", "Recife", "Rio Branco", "Rio de Janeiro", "Salvador", "São Luís", "São Paulo", "Teresina", "Vitória", " " }));
        lblCidadeUser.setToolTipText("");

        try {
            lblDataUser.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        lblDataUser.setText(" dd/mm/yyyy    ");
        lblDataUser.setToolTipText("dd/mm/yyyy");
        lblDataUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblDataUserFocusLost(evt);
            }
        });
        lblDataUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblDataUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtCidade)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblCidadeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTelefoneUser, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txtNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtTelefone))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmailUser))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDataUser, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome)
                            .addComponent(lblNomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail)
                            .addComponent(lblEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefoneUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtData)
                            .addComponent(lblDataUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade)
                    .addComponent(lblCidadeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblNomeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblNomeUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNomeUserActionPerformed

    private void lblTelefoneUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblTelefoneUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTelefoneUserActionPerformed

    private void lblEmailUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblEmailUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblEmailUserActionPerformed

    private void lblDataUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDataUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDataUserActionPerformed

    private void lblDataUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblDataUserFocusLost
        /*Evento que permite deixar o campo data de nascimento vazio.*/
        SimpleDateFormat evento = new SimpleDateFormat("dd/MM/yyyy");
        try{
            Date data_digitada = (Date) evento.parse(lblDataUser.getText());
            lblDataUser.setValue(evento.format(data_digitada));
            }
        catch(ParseException erroEvento){
                lblDataUser.setFocusLostBehavior(lblDataUser.PERSIST);
                lblDataUser.setText(" ");
                lblDataUser.setValue(null);
        }
    }//GEN-LAST:event_lblDataUserFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> lblCidadeUser;
    private javax.swing.JFormattedTextField lblDataUser;
    private javax.swing.JTextField lblEmailUser;
    private javax.swing.JTextField lblNomeUser;
    private javax.swing.JTextField lblTelefoneUser;
    private javax.swing.JLabel txtCidade;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtTelefone;
    // End of variables declaration//GEN-END:variables
}
